"""
Complete database export data for migration purposes.
Contains all 225 institutions from the development database.
"""

def get_complete_migration_data():
    """Return the complete list of 225 institutions for migration"""
    return [
        ('Akron', 'https://gozips.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Alabama', 'https://rolltide.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Alabama A&M Athletics', 'https://aamusports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Alabama State University', 'https://bamastatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Albany', 'https://ualbanysports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Alcorn State', 'https://alcornsports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Appalachian State', 'https://appstatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Arizona', 'https://arizonawildcats.com/sports/2007/8/1/207969432.aspx', 'Matt@ExtraPointsMB.com', None),
        ('Arizona State', 'https://thesundevils.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Arkansas Little Rock', 'https://lrtrojans.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Arkansas Pine Bluff', 'https://uapblionsroar.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Arkansas State University', 'https://astateredwolves.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Auburn', 'https://auburntigers.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Austin Peay', 'https://letsgopeay.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Ball State', 'https://ballstatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Binghamton', 'https://binghamtonbearcats.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Boise State', 'https://broncosports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Bowling Green', 'https://bgsufalcons.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Buffalo', 'https://ubbulls.com/staff-directory', 'Matt@ExtraPointsMB.com', 'LA'),
        ('Cal', 'https://calbears.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Cal Poly', 'https://gopoly.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Cal State Bakersfield', 'https://gorunners.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Cal State Fullerton', 'https://fullertontitans.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Cal State Northridge', 'https://gomatadors.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Central Arkansas', 'https://ucasports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Central Connecticut State University', 'https://ccsubluedevils.com/athletics/directory/index', 'Matt@ExtraPointsMB.com', None),
        ('Central Michigan', 'https://cmuchippewas.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Charlotte', 'https://charlotte49ers.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Chicago State', 'https://www.gocsucougars.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Cincinnati', 'https://gobearcats.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Clemson', 'https://clemsontigers.com/staff-directory/', 'Matt@ExtraPointsMB.com', None),
        ('Cleveland State', 'https://csuvikings.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Coastal Carolina', 'https://goccusports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('College of Charleston', 'https://cofcsports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Colorado', 'https://cubuffs.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Colorado State', 'https://csurams.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Coppin State', 'https://coppinstatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Delaware', 'https://bluehens.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Delaware State', 'https://dsuhornets.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('ECU', 'https://ecupirates.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('EKU', 'https://ekusports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('ETSU', 'https://etsubucs.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('East Texas A&M University', 'https://lionathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Eastern Illinois', 'https://eiupanthers.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Eastern Michigan', 'https://emueagles.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Eastern Washington University', 'https://goeags.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Elon', 'https://elonphoenix.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Evansville', 'https://gopurpleaces.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('FAMU', 'https://famuathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('FAU', 'https://fausports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('FIU', 'https://fiusports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Florida Gulf Coast', 'https://fgcuathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Florida International', 'https://fiusports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Fresno State', 'https://gobulldogs.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('George Mason', 'https://gomason.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Georgia', 'https://georgiadogs.com/staff-directory', 'Matt@ExtraPointsMB.com', 'GA'),
        ('Georgia Southern', 'https://gseagles.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Georgia State', 'https://georgiastatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', 'GA'),
        ('Georgia Tech', 'https://ramblinwreck.com/staff-directory/', 'Matt@ExtraPointsMB.com', None),
        ('Grambling', 'https://gsutigers.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX'),
        ('Hampton', 'https://hamptonpirates.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Hartford', 'https://hartfordhawks.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Hawaii', 'https://hawaiiathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Howard', 'https://howsonbison.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('IU Indy', 'https://iuindyjags.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Idaho State', 'https://isubengals.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Illinois State', 'https://goredbirds.com/staff-directory?path=general', 'Matt@ExtraPointsMB.com', None),
        ('Indiana', 'https://iuhoosiers.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Indiana State', 'https://gosycamores.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Iona', 'https://ionagaels.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Iowa State', 'https://cyclones.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Jackson State', 'https://gojsutigers.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX'),
        ('Jacksonville State', 'https://jaxstatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('James Madison', 'https://jmusports.com/staff-directory', 'Matt@ExtraPointsMB.com', 'VA'),
        ('Kansas', 'https://kuathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Kansas State', 'https://www.kstatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Kennesaw State Athletics', 'https://ksuowls.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Kent State', 'https://kentstatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('LSU', 'https://lsusports.net/staff-directory/', 'Matt@ExtraPointsMB.com', 'LA'),
        ('Lamar', 'https://lamarcardinals.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Long Beach State', 'https://longbeachstate.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Longwood', 'https://longwoodlancers.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Louisiana Tech', 'https://latechsports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('MTSU', 'https://goblueraiders.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Marshall', 'https://herdzone.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('McNeese State', 'https://mcneesesports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Miami OH', 'https://miamiredhawks.com/staff-directory', 'Matt@ExtraPointsMB.com', 'FL'),
        ('Michigan State', 'https://msuspartans.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Mississippi State', 'https://hailstate.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Mississippi State Valley State', 'https://mvsusports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Missouri State', 'https://missouristatebears.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Montana State University', 'https://msubobcats.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Morehead State University', 'https://msueagles.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Morgan State', 'https://morganstatebears.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Murray State', 'https://goracers.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('NJIT', 'https://njithighlanders.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('New Mexico State', 'https://nmstatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Nicholls State', 'https://geauxcolonels.com/staff-directory?path=gen', 'Matt@ExtraPointsMB.com', None),
        ('Norfolk State', 'https://nsuspartans.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('North Carolina A&T', 'https://ncataggies.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('North Carolina Central', 'https://nccueagles.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Northwestern State', 'https://nsudemons.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Ohio', 'https://ohiobobcats.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Ohio State', 'https://ohiostatebuckeyes.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Oklahoma State', 'https://okstate.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Penn State', 'https://gopsusports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Portland State', 'https://goviks.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Prairie View A&M', 'https://pvamu.edu/athletics/staff-directory/', 'Matt@ExtraPointsMB.com', None),
        ('Presbyterian', 'https://gobluehose.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Purdue', 'https://purduesports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Radford', 'https://radfordathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Rhode Island', 'https://gorhody.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Rice', 'https://riceowls.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Richmond', 'https://richmondspiders.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Rutgers', 'https://scarletknights.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Sacramento State', 'https://hornetsports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Sam Houston State', 'https://gobearkats.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('San Diego State', 'https://goaztecs.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('San Jose State', 'https://sjsuspartans.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('South Alabama', 'https://usajaguars.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('South Carolina State', 'https://scsubulldogs.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('South Dakota State', 'https://gojacks.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Southeast Missouri State', 'https://gosoutheast.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Southern Illinois', 'https://siusalukis.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Southern Miss', 'https://southernmiss.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Southern Utah', 'https://suutbirds.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('St. Francis (PA)', 'https://sfuathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Stanford', 'https://gostanford.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Stephen F. Austin', 'https://sfajacks.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Stony Brook', 'https://stonybrookathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Syracuse', 'https://cuse.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('TCU', 'https://gofrogs.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Tennessee State', 'https://tsutigers.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Texas A&M', 'https://12thman.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Texas A&M Commerce', 'https://lionsports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Texas Southern', 'https://tsutigers.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Texas State', 'https://txstatebobcats.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Texas Tech', 'https://texastech.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Towson', 'https://towsontigers.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Troy', 'https://troytrojans.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Tulane', 'https://tulanegreenwave.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Tulsa', 'https://tulsahurricane.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('UAB', 'https://uabsports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('UC Davis', 'https://ucdavisaggies.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('UC Riverside', 'https://gohighlanders.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('UC San Diego', 'https://ucsdtritons.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('UC Santa Barbara', 'https://ucsbgauchos.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('UCF', 'https://ucfknights.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('UCLA', 'https://uclabruins.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('UMBC', 'https://umbcretrievers.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('UMass', 'https://umassathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('UMass Lowell', 'https://goriverhawks.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('UMKC', 'https://umkckangaroos.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('UNLV', 'https://unlvrebels.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('USC', 'https://usctrojans.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('USC Upstate', 'https://upstatespartans.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('UTEP', 'https://utepminers.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('UTRGV', 'https://govaqueros.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('UTSA', 'https://goutsa.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('UW Green Bay', 'https://greenbayphoenix.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('UW Milwaukee', 'https://mkepanthers.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Utah State', 'https://utahstateaggies.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX'),
        ('Utah Tech', 'https://utahtechtrailblazers.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX'),
        ('Utah Valley', 'https://gouvu.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('VCU', 'https://vcuathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', 'VA'),
        ('VMI', 'https://vmikeydets.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Valparaiso', 'https://valpoathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Vanderbilt', 'https://vucommodores.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Vermont', 'https://uvmathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Villanova', 'https://villanova.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Virginia Tech', 'https://hokiesports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Wake Forest', 'https://wakeforest.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Washington', 'https://gohuskies.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Washington State', 'https://wsucougars.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Weber State', 'https://weberstatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('West Virginia', 'https://wvusports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Western Carolina', 'https://catamountsports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Western Illinois', 'https://goleathernecks.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Western Kentucky', 'https://wkusports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Western Michigan', 'https://wmubroncos.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Wichita State', 'https://goshockers.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('William & Mary', 'https://tribeathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Winthrop', 'https://winthropeagles.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Wisconsin', 'https://uwbadgers.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Wright State', 'https://wsuraiders.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Wyoming', 'https://gowyo.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
        ('Youngstown State', 'https://ysusports.com/staff-directory', 'Matt@ExtraPointsMB.com', None),
    ]