-- Complete database migration script with 225 institutions
-- Generated on: 2025-08-18 00:38:46

-- Clear existing data (optional)
DELETE FROM monitored_url;
DELETE FROM staff_change;
DELETE FROM scraping_log;

-- Insert all 225 URLs from development database
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Alabama State University', 'https://bamastatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Alcorn State', 'https://alcornsports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Appalachian State', 'https://appstatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Arizona State', 'https://thesundevils.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Arkansas State University', 'https://astateredwolves.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Auburn', 'https://auburntigers.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Austin Peay', 'https://letsgopeay.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Arizona', 'https://arizonawildcats.com/sports/2007/8/1/207969432.aspx', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Ball State', 'https://ballstatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Binghamton', 'https://binghamtonbearcats.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Boise State', 'https://broncosports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Bowling Green', 'https://bgsufalcons.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Alabama A&M Athletics', 'https://aamusports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Cal Poly', 'https://gopoly.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Cal State Bakersfield', 'https://gorunners.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Fresno State', 'https://gobulldogs.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Cal State Fullerton', 'https://fullertontitans.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Cal State Northridge', 'https://gomatadors.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Sacramento State', 'https://hornetsports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Central Connecticut State University', 'https://ccsubluedevils.com/athletics/directory/index', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Central Michigan', 'https://cmuchippewas.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Chicago State', 'https://www.gocsucougars.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Clemson', 'https://clemsontigers.com/staff-directory/', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Cleveland State', 'https://csuvikings.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Coastal Carolina', 'https://goccusports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('College of Charleston', 'https://cofcsports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Colorado State', 'https://csurams.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Coppin State', 'https://coppinstatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Colorado', 'https://cubuffs.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('ECU', 'https://ecupirates.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('ETSU', 'https://etsubucs.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('East Texas A&M University', 'https://lionathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Eastern Illinois', 'https://eiupanthers.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('EKU', 'https://ekusports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Eastern Michigan', 'https://emueagles.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Eastern Washington University', 'https://goeags.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('FAMU', 'https://famuathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('FAU', 'https://fausports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Florida Gulf Coast', 'https://fgcuathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Florida International', 'https://fiusports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('George Mason', 'https://gomason.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Georgia Tech', 'https://ramblinwreck.com/staff-directory/', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Georgia Southern', 'https://gseagles.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Georgia State', 'https://georgiastatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', 'GA', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Georgia', 'https://georgiadogs.com/staff-directory', 'Matt@ExtraPointsMB.com', 'GA', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Grambling', 'https://gsutigers.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Idaho State', 'https://isubengals.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Illinois State', 'https://goredbirds.com/staff-directory?path=general', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Indiana State', 'https://gosycamores.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Indiana', 'https://iuhoosiers.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Iowa State', 'https://cyclones.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('IU Indy', 'https://iuindyjags.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Jackson State', 'https://gojsutigers.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Jacksonville State', 'https://jaxstatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('James Madison', 'https://jmusports.com/staff-directory', 'Matt@ExtraPointsMB.com', 'VA', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Kansas State', 'https://www.kstatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Kansas', 'https://kuathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Kennesaw State Athletics', 'https://ksuowls.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Kent State', 'https://kentstatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Lamar', 'https://lamarcardinals.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Long Beach State', 'https://longbeachstate.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Longwood', 'https://longwoodlancers.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('LSU', 'https://lsusports.net/staff-directory/', 'Matt@ExtraPointsMB.com', 'LA', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Louisiana Tech', 'https://latechsports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Marshall', 'https://herdzone.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('McNeese State', 'https://mcneesesports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Miami OH', 'https://miamiredhawks.com/staff-directory', 'Matt@ExtraPointsMB.com', 'FL', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Michigan State', 'https://msuspartans.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('MTSU', 'https://goblueraiders.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Mississippi State', 'https://hailstate.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Mississippi State Valley State', 'https://mvsusports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Missouri State', 'https://missouristatebears.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Montana State University', 'https://msubobcats.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Morehead State University', 'https://msueagles.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Morgan State', 'https://morganstatebears.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Murray State', 'https://goracers.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('NJIT', 'https://njithighlanders.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('New Mexico State', 'https://nmstatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Nicholls State', 'https://geauxcolonels.com/staff-directory?path=gen', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Norfolk State', 'https://nsuspartans.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('NC A&T', 'https://ncataggies.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('NC Central', 'https://nccueaglepride.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('NC State', 'https://gopack.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('North Dakota State', 'https://gobison.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Northern Arizona', 'https://nauathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', 'AZ', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Northern Illinois', 'https://niuhuskies.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Northern Kentucky', 'https://nkunorse.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Northwestern State', 'https://nsudemons.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Oakland', 'https://goldengrizzlies.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Ohio University', 'https://ohiobobcats.com/staff-directory', 'Matt@ExtraPointsMB.com', 'OH', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Ohio State', 'https://ohiostatebuckeyes.com/staff-directory', 'Matt@ExtraPointsMB.com', 'OH', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Oklahoma State', 'https://okstate.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Old Dominion', 'https://odusports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Oregon State', 'https://osubeavers.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Portland State', 'https://goviks.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Prairie View A&M', 'https://pvpanthers.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Purdue', 'https://purduesports.com/staff-directory', 'Matt@ExtraPointsMB.com', 'IN', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Purdue Ft. Wayne', 'https://gomastodons.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Radford', 'https://radfordathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Rutgers', 'https://scarletknights.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Sam Houston State', 'https://gobearkats.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('San Diego State', 'https://goaztecs.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('San Jose State', 'https://sjsuspartans.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('South Carolina State', 'https://www.scsuathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('South Dakota State', 'https://gojacks.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Southeast Missouri State', 'https://semoredhawks.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Southeast Louisiana', 'https://lionsports.net/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Southern Illinois', 'https://siusalukis.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Southern Illinois - Edwardsville', 'https://siuecougars.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Southern', 'https://gojagsports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Southern Utah', 'https://suutbirds.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Stephen F. Austin State University', 'https://sfajacks.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Stony Brook', 'https://stonybrookathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Tarleton State', 'https://tarletonsports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Tennessee State', 'https://tsutigers.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Tennessee Tech', 'https://www.ttusports.com/information/directory/index', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Texas A&M', 'https://12thman.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Texas A&M CC', 'https://goislanders.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Texas Southern', 'https://tsusports.com/staff-directory', 'matt@extrapointsmb.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Texas State', 'https://txst.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Texas Tech', 'https://texastech.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('The Citadel', 'https://citadelsports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Charlotte', 'https://charlotte49ers.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UNC Greensboro', 'https://uncgspartans.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Southern Miss', 'https://southernmiss.com/staff-directory', 'Matt@ExtraPointsMB.com', 'MS', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UTRGV', 'https://goutrgv.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Towson', 'https://towsontigers.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Troy', 'https://troytrojans.com/staff-directory', 'Matt@ExtraPointsMB.com', 'AL', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Albany', 'https://ualbanysports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Buffalo', 'https://ubbulls.com/staff-directory', 'Matt@ExtraPointsMB.com', 'LA', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Akron', 'https://gozips.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Alabama', 'https://rolltide.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UAB', 'https://uabsports.com/staff-directory', 'Matt@ExtraPointsMB.com', 'AL', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Arkansas Little Rock', 'https://lrtrojans.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Arkansas Pine Bluff', 'https://uapblionsroar.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Cal', 'https://calbears.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UC Davis', 'https://ucdavisaggies.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UC Irvine', 'https://ucirvinesports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UCLA', 'https://uclabruins.com/staff-directory', 'Matt@ExtraPointsMB.com', 'CA', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UC Riverside', 'https://gohighlanders.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UC San Diego', 'https://ucsdtritons.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UC Santa Barbara', 'https://ucsbgauchos.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Central Arkansas', 'https://ucasports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Cincinnati', 'https://gobearcats.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UConn', 'https://uconnhuskies.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Hawaii', 'https://hawaiiathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Houston', 'https://uhcougars.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Idaho', 'https://govandals.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Illinois', 'https://fightingillini.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UIC', 'https://uicflames.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Iowa', 'https://hawkeyesports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Kentucky', 'https://ukathletics.com/staff-directory/', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Louisiana Lafayette', 'https://ragincajuns.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Louisiana Monroe', 'https://ulmwarhawks.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Louisville', 'https://gocards.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Maine', 'https://goblackbears.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Maryland Eastern Shore', 'https://umeshawksports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UMBC', 'https://umbcretrievers.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UMass Lowell', 'https://goriverhawks.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UMass', 'https://umassathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Memphis', 'https://gotigersgo.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Michigan', 'https://mgoblue.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Minnesota', 'https://gophersports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Ole Miss', 'https://olemisssports.com/staff-directory', 'Matt@ExtraPointsMB.com', 'MS', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UMKC', 'https://kcroos.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Missouri', 'https://mutigers.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Montana', 'https://gogriz.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Nebraska-Omaha', 'https://omavs.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Nebraska', 'https://huskers.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UNLV', 'https://unlvrebels.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Nevada', 'https://nevadawolfpack.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('New Hampshire', 'https://unhwildcats.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('New Mexico', 'https://golobos.com/staff-directory/', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('New Orleans', 'https://unoprivateers.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('North Alabama', 'https://roarlions.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UNC Asheville', 'https://uncabulldogs.com/staff-directory', 'Matt@ExtraPointsMB.com', 'LA', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UNC Wilmington', 'https://uncwsports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UNC', 'https://goheels.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('North Dakota', 'https://fightinghawks.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('North Florida', 'https://unfospreys.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('North Texas', 'https://meangreensports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Northern Colorado', 'https://uncbears.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Northern Iowa', 'https://unipanthers.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Oklahoma', 'https://soonersports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Oregon', 'https://goducks.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Rhode Island', 'https://gorhody.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('South Alabama', 'https://usajaguars.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('South Carolina Upstate', 'https://upstatespartans.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('South Carolina', 'https://gamecocksonline.com/staff-directory/', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('South Dakota', 'https://goyotes.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('South Florida', 'https://gousfbulls.com/staff-directory', 'Matt@ExtraPointsMB.com', 'FL', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Tennessee Chattanooga', 'https://gomocs.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Tennessee Martin', 'https://utmsports.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Tennessee', 'https://utsports.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UT Arlington', 'https://utamavs.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Texas', 'https://texaslonghorns.com/staff-directory?path=general', 'Matt@ExtraPointsMB.com', 'TX', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UTEP', 'https://utepminers.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UTSA', 'https://goutsa.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Toledo', 'https://utrockets.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Utah', 'https://utahutes.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Vermont', 'https://uvmathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Virginia', 'https://virginiasports.com/staff-directory/', 'Matt@ExtraPointsMB.com', 'VA', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Washington', 'https://gohuskies.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('West Georgia', 'https://uwgathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UW Green Bay', 'https://greenbayphoenix.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Wisconsin', 'https://uwbadgers.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('UW Milwaukee', 'https://mkepanthers.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Wyoming', 'https://gowyo.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Utah State', 'https://utahstateaggies.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Utah Tech', 'https://utahtechtrailblazers.com/staff-directory', 'Matt@ExtraPointsMB.com', 'TX', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Utah Valley', 'https://gouvu.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('VCU', 'https://vcuathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', 'VA', true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('VMI', 'https://vmikeydets.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Virginia Tech', 'https://hokiesports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Weber State', 'https://weberstatesports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('West Virginia', 'https://wvusports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Western Carolina', 'https://catamountsports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Western Illinois', 'https://goleathernecks.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Western Kentucky', 'https://wkusports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Western Michigan', 'https://wmubroncos.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Wichita State', 'https://goshockers.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('William & Mary', 'https://tribeathletics.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Winthrop', 'https://winthropeagles.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Wright State', 'https://wsuraiders.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
INSERT INTO monitored_url (name, url, email, state, is_active, created_at) VALUES ('Youngstown State', 'https://ysusports.com/staff-directory', 'Matt@ExtraPointsMB.com', NULL, true, NOW());
